In [1]:
!pip install --user keras-self-attention

In [12]:
import keras
from keras_self_attention import SeqSelfAttention,ScaledDotProductAttention
timesteps, input_dim = 60,3

model = keras.models.Sequential()
# model.add(keras.layers.Embedding(input_dim=10000,
#                                  output_dim=300,
#                                  mask_zero=True))
# model.add(keras.layers.Input(shape=(timesteps, input_dim)))
model.add(keras.layers.LSTM(units=128,input_shape=(timesteps,input_dim),
                                                       return_sequences=True))
model.add(keras.layers.Flatten())
model.add(ScaledDotProductAttention())
model.add(keras.layers.Dense(units=5))
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['categorical_accuracy'],
)
model.summary()

IndexError: tuple index out of range

In [13]:
import keras.backend as K

In [15]:
a = K.zeros((5,6))

In [27]:
b = np.array(K.eval(a))

In [20]:
import numpy as np

In [29]:
c = K.variable(b)

In [30]:
a,c

(<tf.Variable 'Variable:0' shape=(5, 6) dtype=float32, numpy=
 array([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]], dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(5, 6) dtype=float32, numpy=
 array([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]], dtype=float32)>)

In [31]:
a

<tf.Variable 'Variable:0' shape=(5, 6) dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [25]:
b

IndexError: too many indices for array